apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
      - name: community
        image: your-registry/community:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: community-service
spec:
  selector:
    app: community
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000