apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: your-registry/library:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000