apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: your-registry/training:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: training-service
spec:
  selector:
    app: training
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000